services:
#  db_admin:
#    image: coleifer/sqlite-web
#    ports:
#      - 8080:8080
#    environment:
#      SQLITE_DATABASE: "db.sqlite"
#    volumes:
#      - ./app/data:/data

  app:
    build:
      context: .
    volumes:
      - ./app/data:/usr/src/app/data
    entrypoint: [ "python", "app.py" ]
    env_file: ./app/.env
    restart: on-failure
