services:
  db_admin:
    image: coleifer/sqlite-web
    ports:
      - 8080:8080
    environment:
      SQLITE_DATABASE: "db.sqlite"
    volumes:
      - db:/data

  app:
    build:
      context: .
    volumes:
      - db:/usr/src/app/const
    entrypoint: ["python", "app.py"]
    env_file: ./app/.env

volumes:
  db: